const blogPosts = [
    {
        "ID": "0",
        "TITLE": "Test Blog Post 1",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "STATUS": "Status good",
        "IMAGE_1": "../img/fire.jpg",
        "IMAGE_2": "../img/test_image_square.jpg",
        "IMAGE_3": "../img/community_outreach.PNG",
        "PROBLEM": "This currently doesn't work",
        "SOLUTION": "Make it work",
        "SKILLS_USED": "Literally used every single skill on the planet",
        "FUTURE": "You never know what the future will hold!",
        "SINGLE_PICTURE_GRID": {
            "IMAGE": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
        "TWO_PICTURE_GRID": {
            "IMAGE_ONE": "../img/test_image_wide.jpg", 
            "IMAGE_TWO": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
    {
        "ID": "1",
        "TITLE": "First Entry",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "STATUS": "Under Construction",
        "IMAGE_1": "../img/building_website_screenshot1.png",
        "IMAGE_2": "../img/building_website_screenshot2.png",
        "IMAGE_3": "../img/building_website_screenshot3.png",
        "PROBLEM": "I need to have a website to display my protfolio. I also despise web development on the upmost level",
        "SOLUTION": "I'm building one! And learning a bit of web development along the way",
        "SKILLS_USED": "This project like most basic websites is a fun cocktail of html/css/javascript.",
        "FUTURE": "I really really really want to finish this website so that I never have to touch web dev again",
    },
    {
        "ID": "2",
        "TITLE": "Trail Building",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "STATUS": "On Going",
        "IMAGE_1": "../img/trail_building_washington/moss_remove.jpg",
        "IMAGE_2": "../img/trail_building_washington/grimice1.jpg",
        "IMAGE_3": "../img/trail_building_washington/grimice2.jpg",
        "PROBLEM": "Simple put, there will never be enough trails! Mountain biking is a unique outdoor sport because it relies on trail building to exist. Also, already built trails do not last forever and need maintenance often. This comes in many forms, whether it is cutting back overgrown foliage, fixing drains for water runoff, replacing dirt where it has eroded and sometimes rerouting sections of trail that just don’t quite “flow”. There is no shortage of labor needed to keep mountain biking fun, unique, and safe through trail building. ",
        "SOLUTION": "I love creating in all aspects of my life, so I naturally gravitated toward trail building. Winter offers a perfect time for trail building or as it’s often called “digging”. During a hard rain, it is often much easier to motivate to dig than ride. Moisture helps make the soil easier to shape. I try to divide my time between building new trails and maintaining old ones. Digging takes a lot of labor, and I will often recruit medium-sized groups from the community to help with projects. Not everybody needs to spend all their time digging, it is nice to give these people an easy chance to help out without being overwhelmed.",
        "SKILLS_USED": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "FUTURE": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "TWO_PICTURE_GRID": {
            "IMAGE_ONE": "../img/trail_building_washington/logs.jpg", 
            "IMAGE_TWO": "../img/trail_building_washington/berm.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
        "SINGLE_PICTURE_GRID" : {
            "IMAGE": "../img/trail_building_washington/drop.JPG",
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        }
    },
    {
        "ID": "3",
        "TITLE": "Community Outreach",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "STATUS": "Status good",
        "IMAGE_1": "../img/community_outreach.PNG",
        "IMAGE_2": "../img/fire.jpg",
        "IMAGE_3": "../img/test_image_wide.jpg",
        "PROBLEM": "This currently doesn't work",
        "SOLUTION": "Make it work",
        "SKILLS_USED": "Literally used every single skill on the planet",
        "FUTURE": "You never know what the future will hold!",
        "SINGLE_PICTURE_GRID": {
            "IMAGE": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
        "TWO_PICTURE_GRID": {
            "IMAGE_ONE": "../img/test_image_wide.jpg", 
            "IMAGE_TWO": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
    {
        "ID": "4",
        "TITLE": "Riding in Desert",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "STATUS": "Status good",
        "IMAGE_1": "../img/bike_desert.JPEG",
        "IMAGE_2": "../img/bike_jumping.jpg",
        "IMAGE_3": "../img/bike_yakima.JPEG",
        "PROBLEM": "This currently doesn't work",
        "SOLUTION": "Make it work",
        "SKILLS_USED": "Literally used every single skill on the planet",
        "FUTURE": "You never know what the future will hold!",
        "SINGLE_PICTURE_GRID": {
            "IMAGE": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
        "TWO_PICTURE_GRID": {
            "IMAGE_ONE": "../img/test_image_wide.jpg", 
            "IMAGE_TWO": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
    {
        "ID": "5",
        "TITLE": "Binary Clock",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "STATUS": "Status good",
        "IMAGE_1": "../img/clock.gif",
        "IMAGE_2": "../img/building_website_screenshot1.png",
        "IMAGE_3": "../img/fire.jpg",
        "PROBLEM": "This currently doesn't work",
        "SOLUTION": "Make it work",
        "SKILLS_USED": "Literally used every single skill on the planet",
        "FUTURE": "You never know what the future will hold!",
        "SINGLE_PICTURE_GRID": {
            "IMAGE": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
        "TWO_PICTURE_GRID": {
            "IMAGE_ONE": "../img/test_image_wide.jpg", 
            "IMAGE_TWO": "../img/test_image_wide.jpg", 
            "TEXT": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
];