const mainText = {
    "MAIN_IMAGE": "img/bike_riding/main_picture_3.jpg",
    "ABOUT_IMAGE": "img/random/main_picture.jpg",
    "INTRO_TEXT": "My name is Jason Kasari, and I’m a software developer/bike industry professional/chimney sweep/lifelong learner. I am passionate about engaging in new ideas and about working alongside others to solve problems.",
    "ABOUT_TEXT": "My career in the bike industry began when I was 14 and volunteered for my community by rebuilding bikes for those in a low-income bracket. Riding my own bike 9 miles each way to this entry-level job, gave me the experience I needed to get my foot in the door of the bike industry. I quickly moved into a retail bike shop and started by building bikes out of the box, working my way up to bike mechanic. I was very young, working with adults, I earned myself a ton of nicknames, and became an integral part of the shop. I really felt at home in the bike industry and began traveling around to different bike riding spots. A favorite was Bellingham. At this time, I was working with a lot of people with college degrees that didn’t relate to their work. Because of this, when I finished my Associate's degree I moved to Bellingham to keep working in bike shops and gain life experiences until I found something worth returning to school for. I loved working in bike shops but always had it in the back of my head that I wanted to do more. So when a buddy talked to me about his path of learning software, my puzzle-hungry brain jumped on board. I have now successfully worked as a web developer for a bike shop and currently work part-time on embedded systems at a marine biology start-up. Learning software has been such a fun challenge and I feel as though I am only getting started with my new career which I hope will allow me to continue to pursue all the things I enjoy outside of work. A work-life balance is incredibly important to me. I enjoy disappearing into the woods as often as I can. Camping with friends and riding bikes in cool locations is what I live for. I always have a camping set up in whatever car I own at the time and use it to explore new locations. Outside of riding, I spend a good amount of time contributing to the many trails we have in Bellingham, maintaining the old while sometimes creating new ones. I am always looking for new outlets for my desire to create. Outside is fun but I also enjoy sitting inside and solving a good hard problem on whatever project I am currently working on. I’m constantly looking for an excuse to break out the 3D printer and solder. I recently created an autonomous light system for my commuter bike. Using technology to create a system that manages to slip into the background and subtly does its job is something I get a kick out of. With software, I hope to continue to bridge the gap between fun projects and work projects. I have lofty goals for where I want to end up in life and continue to put the work in to make them happen!!",
    "EMAIL": "email | jkasari@outlook.com",
    "PHONE": "phone | 541-610-5575",
    "GITHUB": "github | jkasari",
}

const colors = {
    "COLOR_1": "#C7CACC",
    "COLOR_2": "#202d31",
    "COLOR_3": "#F1CB24",

}

const blogPosts = [
    {
        "ID": "0",
        "TITLE": "Marine Cytometery",
        "TITLE_COLOR": "COLOR_1",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "TILE_IMAGE": "img/marcy/lights_on_good.jpg",
        "HEADER_IMAGE": "img/marcy/lab1.jpg",
        "CONTENT": {
            "TEXT_1": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_1": "img/marcy/lights_compared.jpg",
            "TITLE_1": "This is a Test Title",
            "TEXT_2": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_2": "img/marcy/first_pcb_intub.jpg",
            "TEXT_3": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "TEXT_4": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_3": "img/marcy/fluidics_board_1.jpg",
            "TEXT_5": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
    {
        "ID": "1",
        "TITLE": "Binary Clock",
        "TITLE_COLOR": "COLOR_1",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "TILE_IMAGE": "img/binary_clock/clock.gif",
        "HEADER_IMAGE": "img/random/test_image_background.png",
        "CONTENT": {
            "IMAGE_1": "img/random/test_image_wide.jpg",
            "TITLE_1": "This is a Test Title",
            "TEXT_1": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
    {
        "ID": "2",
        "TITLE": "Bike Industry",
        "TITLE_COLOR": "COLOR_1",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "TILE_IMAGE": "img/working_bike_industry/tire_slide.gif",
        "HEADER_IMAGE": "img/random/test_image_background.png",
        "CONTENT": {
            "IMAGE_1": "img/random/test_image_wide.jpg",
            "TITLE_1": "This is a Test Title",
            "TEXT_1": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
    {
        "ID": "3",
        "TITLE": "Learning Software",
        "TITLE_COLOR": "COLOR_1",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "TILE_IMAGE": "img/learning_electronics/passing_test.jpg",
        "HEADER_IMAGE": "img/random/test_image_background.png",
        "CONTENT": {
            "IMAGE_1": "img/random/test_image_wide.jpg",
            "TITLE_1": "This is a Test Title",
            "TEXT_1": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
    },
    {
        "ID": "4",
        "TITLE": "Hill Top Bike Park",
        "TITLE_COLOR": "COLOR_1",
        "TILE_TEXT": "- A small blerb about that thing I did.",
        "TILE_IMAGE": "img/trail_building_alaska/mini_ex.jpg",
        "HEADER_IMAGE": "img/trail_building_alaska/rock_lip.jpg",
        "CONTENT": {
            "TITLE_1": "This is a Test Title",
            "IMAGE_1": "img/trail_building_alaska/orange_mini.jpg",
            "TEXT_1": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "TEXT_2": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_2": "img/trail_building_alaska/pump_track.jpg",
            "IMAGE_3": "img/trail_building_alaska/rock_garden.jpg",
            "TEXT_3": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "TITLE_2": "This is a Test Title",
            "TEXT_4": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_4": "img/trail_building_alaska/mini_ex.jpg",
            "TEXT_5": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_5": "img/trail_building_alaska/bug_net.jpg",
        },
    },
    {
        "ID": "5",
        "TITLE": "Trail Building",
        "TITLE_COLOR": "COLOR_3",
        "TILE_TEXT": "- Trails don't build themselves.",
        "TILE_IMAGE": "img/trail_building_washington/moss_remove.jpg",
        "HEADER_IMAGE": "img/trail_building_washington/chainsaw_1.jpg",
        "CONTENT": {
            "TITLE_1": "This is a Test Title",
            "TEXT_1": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_1": "img/trail_building_washington/logs.jpg",
            "TEXT_2": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "TEXT_3": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_2": "img/trail_building_washington/grimice1.jpg",
            "IMAGE_3": "img/trail_building_washington/cougar_jump.jpg",
            "TITLE_2": "This is a Test Title",
            "TEXT_4": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "TITLE_3": "This is a Test Title",
            "TEXT_5": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_4": "img/trail_building_washington/rock-done-v-raw.JPG",
        },
    },
    {
        "ID": "6",
        "TITLE": "Custom Hardtail",
        "TITLE_COLOR": "COLOR_2",
        "TILE_TEXT": "- Designing and building a Dh hartail.",
        "TILE_IMAGE": "img/ferrous/v2_fancy1.jpg",
        "HEADER_IMAGE": "img/ferrous/v2_fancy2.jpg",
        "CONTENT": {
            "TITLE_1": "This is a Test Title",
            "TEXT_1": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_1": "img/ferrous/v2_benchtop.JPG",
            "TEXT_2": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_2": "img/bike_riding/bike_jumping.jpg",
            "TEXT_3": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_4": "img/ferrous/fix_me_plz.jpg",
            "IMAGE_3": "img/ferrous/v1_v2_sidebyside.jpg",
            "TEXT_4": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "TITLE_2": "This is a Test Title",
            "TEXT_5": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "TEXT_6": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "IMAGE_5": "img/ferrous/headtube_badge.jpg",
        }
    },
];